server: 
    name: GOST Server
    host: localhost
    port: 8080
    externalUri: http://localhost:8080/
database:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: gost
    schema: v1
    ssl: false
mqtt:
    enabled: true
    webSocketEnabled: true
    secureWebSocketEnabled: false
    port: 1883
    webSocketPort:  8081
    secureWebSocketPort: 8082
    keepAlive: 300
    connectTimeout: 2
    ackTimeout: 20
    timeoutRetries: 3
    secureWebSocketCertPath:
    secureWebSocketKeyPath: