server:
    name: GOST Server
    host: localhost
    port: 8080
    externalUri: localhost:8080/
database:
    host: 192.168.40.10
    port: 5432
    user: postgres
    password: postgres
    database: gost
    schema: v1
    ssl: false