server:
    name: GOST Server
    host: localhost
    port: 8080
    externalUri: localhost:8080/
database:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: 
    database: gost
    schema: v1
    ssl: false