[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/gost/godata"

[[constraint]]
  branch = "master"
  name = "github.com/gost/core"

[[constraint]]
  name = "github.com/gost/now"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
