server: 
    name: GOST Server
    host: localhost
    port: 8080
    externalUri: http://localhost:8080/
database:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: gost
    schema: v1
    ssl: false
mqtt:
    enabled: true
    host: iot.eclipse.org
    port: 1883