server: 
    name: GOST Server
    host: 
    port: 8080
    externalUri: http://localhost:8080/
    clientContent: ./client/
    maxEntityResponse: 20
    indentedJson: true
database:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: postgres
    schema: v1
    ssl: false
    maxIdleConns: 30
    maxOpenConns: 100
mqtt:
    enabled: true
    host: 127.0.0.1
    port: 1883