server:
    name: GOST Server
    host: localhost
    port: 8080
    externalUri: http://localhost:8080/
    maxEntityResponse: 20
    indentedJson: true
database:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password:
    database: gost
    schema: v1
    ssl: false
    maxIdleConns: 50
    maxOpenConns: 100
mqtt:
    enabled: true
    host: iot.eclipse.org
    port: 1883