version: '2'
services:
    node-red:
        image: nodered/node-red-docker
        ports:
            - "1880:1880"
    mosquitto:
        image: toke/mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
    gost-db:
        image: geodan/gost-db
        volumes_from:
            - pg_data        
        ports:
            - "5432:5432"
        environment:
            PGDATA : /var/lib/postgresql/data/pgdata
    web_app:
        image: geodan/gost
        ports:
            - "8080:8080"
        depends_on:
            - mosquitto
            - gost-db
        links:
            - gost-db
        environment: 
            gost_db_host: gost-db            
    pg_data:
        restart: always
        image: alpine
        volumes: 
            - /var/lib/postgresql/data/pgdata
        command: "true"
