version: '2'
services:
    mosquitto:
        image: toke/mosquitto
        ports:
            - "1883:1883"
            - "9001:9001" 
    postgis1:
        build: ./docker/postgis
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_DB: gost            
    web_app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - mosquitto
        links:
            - postgis1
